
name: Release Management

on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: main
  push:
    branches:
      - main

jobs:
  update_draft_release:
    name: Update Draft Release
    if: ((github.event_name == 'workflow_call') && (github.ref_name == inputs.branch) )|| github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      # Drafts your next Release notes as Pull Requests are merged
      - uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disable-autolabeler: true